name: Scheduled Publish

on:
  schedule:
    - cron: '22 4 * * 0'  # Weekly build
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [blueteamer, bountyhunter, cracker, dos, forensic, malware, mobile, network, osint, redteamer, student, web]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.role }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.role }}
          push: true
          tags: athenaos/${{ matrix.role }}:latest
