name: Scheduled Publish

on:
  schedule:
    - cron: '22 4 * * 0'  # Weekly build
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Ensure all matrix jobs continue even if one fails
  matrix:
    include:
      - role: "blue"
        job_name: "💙 Blue Teamer 💙"
      - role: "bugbounty"
        job_name: "🐞 Bug Bounty Hunter 🐞"
      - role: "cracker"
        job_name: "🍘 Cracker Specialist 🍘"
      - role: "dos"
        job_name: "💀 DoS Tester 💀"
      - role: "student"
        job_name: "🎓 Enthusiast Student 🎓"
      - role: "forensic"
        job_name: "🔍 Forensic Analyst 🔍"
      - role: "malware"
        job_name: "🦠 Malware Analyst 🦠"
      - role: "mobile"
        job_name: "📱 Mobile Analyst 📱"
      - role: "network"
        job_name: "🌐 Network Analyst 🌐"
      - role: "osint"
        job_name: "🕵️ OSINT Specialist 🕵️"
      - role: "red"
        job_name: "❤️ Red Teamer ❤️"
      - role: "web"
        job_name: "🕸️ Web Pentester 🕸️"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.role }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.role }}
          push: true
          tags: athenaos/${{ matrix.role }}:latest
